LogisticRegression:
  random_state: 16
  C: 0.1
  penalty: 'l2'
  dual: False
  tol: 0.0001
  fit_intercept: True
  intercept_scaling: 1
  class_weight: None
  solver: 'liblinear'
  max_iter: 100
  multi_class: 'auto'
  verbose: 0
  warm_start: False
  n_jobs: None
  l1_ratio: None 