COLUMNS:

  BloodPressure: float64
  SkinThickness: float64
  Insulin: float64
  BMI: float64
  DiabetesPedigreeFunction: float64
  Age: float64
  Outcome: float64


TARGET_COLUMN:
  name: Outcome
  
